title: tinywn
description: mad love
url:              
baseurl: 
signoff: WN
encoding: utf-8
links:
  
  - name: Blog
    url: /
  - name: GitHub
    url: http://github.com/tinywn
    external: true

pygments: true
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions:     [autolink, tables]
