markdown: rdiscount
permalink: /:title/
url: http://tinywn.github.io
name: tinywn.cc
author: tinywn
qq: 773963322
email: codecup@163.com
weibo: 3842200194
github: tinywn
pygments: true
safe: true
paginate: 20
truncate: 200
