markdown: rdiscount
permalink: /:title/
url: http://tinywn.github.io
name: tinywn
author: wn
qq: 
email: 
duoshuo: 
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo:
github: 
pygments: true
safe: true
paginate: 20
about: "小菜"
