markdown: rdiscount
permalink: /:title/
url: http://tinywn.github.io
name: tinywn
author: tinywn
qq: 773963322
email: codecup@163.com
duoshuo: tinywn
weibo: 3842200194
github: tinywn
pygments: true
safe: true
paginate: 20
